### ISSUE TITLE
Trouble connecting to Faktory via docker-compose

### ISSUE THREAD

**Issue by jer-k** [seated/faktory_worker#93]
I'm trying to get my application running via `docker-compose` and for some reason I cannot figure out why Phoenix can't push jobs into the queue. 
My `docker-compose` looks like this
```
version: '3'

services:
  my_app:
    build: .
    command: mix phx.server  
    ports:
      - '4000:4000'
    depends_on:
      - faktory    

  faktory:
    image: contribsys/faktory
    ports:
      - '7420:7420'
      - '7419:7419' 
```

And in my `application.ex` I have
```
  def start(_type, _args) do
    children = [
       ...
      {FaktoryWorker, [
        connection: [
          host: "faktory"
        ],
        worker_pool: [
        size: 5,
        queues: ["my_queue"]
      ]]}
    ]
```
Am I wrong in thinking that the host is supposed to be `faktory`?  When I `docker-compose up` I can open the `http://localhost:7420/` and see that Faktory is indeed running. 

Then I open up an `iex` session on the Phoenix container and attempt to push a job.
```
iex(1)> :ok = MyApp.Workers.MyJob.perform_async()     
:ok
```
I go back to the Faktory dashboard and I don't see anything having been enqueued or run.
![image](https://user-images.githubusercontent.com/1280586/80319727-d41a7700-87c6-11ea-8cf0-366a1657f975.png)
